version: "3"
services:
  db:
    image: postgres:10
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  migration:
    image: node:14.17.0-alpine3.13
    command: yarn migration:run
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./backend/.env.example

  backend:
    image: node:14.17.0-alpine3.13
    command: yarn start:dev
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "3001"
    ports:
      - "3001:3001"
    depends_on:
      - migration
    env_file:
      - ./backend/.env.example
