version: "3"
services:
  db_beer:
    image: postgres:10
    volumes:
      - ./db:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  db_vine:
    image: postgres:10
    volumes:
      - ./db1:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  migration_beer:
    image: node:14.17.0-alpine3.13
    command: yarn migration-beer:run
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    links:
      - db_beer
    depends_on:
      - db_beer
    env_file:
      - ./backend/.env.example

  migration_vine:
    image: node:14.17.0-alpine3.13
    command: yarn migration-vine:run
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    links:
      - db_vine
    depends_on:
      - db_vine
    env_file:
      - ./backend/.env.example

  seed:
    image: node:14.17.0-alpine3.13
    command: yarn migration:seed
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    links:
      - db_beer
      - db_vine
    depends_on:
      - migration_beer
      - migration_vine
    env_file:
      - ./backend/.env.example

  backend:
    image: node:14.17.0-alpine3.13
    command: yarn start:dev
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    expose:
      - "3001"
    ports:
      - "3001:3001"
    links:
      - db_beer
      - db_vine
    depends_on:
      - migration_beer
      - migration_vine
    env_file:
      - ./backend/.env.example

  frontend:
    image: node:14.17.0-alpine3.13
    command: yarn dev
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - backend
