import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'

import { Beer } from '@backend/beer/beer.entity'
import BeerInfo from '@components/BeerInfo'
import LoadingBox from '@components/LoadingBox'
import beerService from '@services/beer.service'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [beers, setBeer] = useState<Beer[]>([])
  const [isLoading, setIsLoading] = useState<Boolean>(false)

  const getRandomBeer = () => {
    setIsLoading(true)

    const delaySecond = 0.5
    beerService
      .getRandomBeer(delaySecond)
      .then((beerFromApi) => beerFromApi && setBeer([beerFromApi, ...beers]))
      .finally(() => setIsLoading(false))
  }

  const onNextButtonClick = () => getRandomBeer()
  const onPrevButtonClick = () => {
    const isAbleToCallPreviousBeer = !beers || beers.length === 1
    if (isAbleToCallPreviousBeer === true) {
      return
    }

    const [, ...restBeers] = beers
    setBeer(restBeers)
  }

  const [currentBeerInfo] = beers
  const isButtonPrevDisabled = beers && beers.length <= 1
  const isShowLoadingBox = isLoading === true
  const isShowBeerInfo = isLoading !== true

  useEffect(function onInitPage() {
    getRandomBeer()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Beer App</title>
        <meta name="description" content="Generated by Beer app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} md:border-2 px-2 rounded-md`}>
        {isShowLoadingBox && <LoadingBox />}

        {isShowBeerInfo && (
          <div className="flex">
            <BeerInfo beer={currentBeerInfo} />
          </div>
        )}

        <div className="flex w-full">
          <button
            className={styles.card}
            onClick={onPrevButtonClick}
            disabled={isButtonPrevDisabled}
          >
            Prev
          </button>
          <button className={styles.card} onClick={onNextButtonClick}>
            Next
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
